
package employee_ms.controller;

import employee_ms.model.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class reset_password extends javax.swing.JFrame {

    /**
     * Creates new form reset_password
     */
    public reset_password() {
        initComponents();
    }

       
    //Validation
    public boolean validateInputs(){
       
      String username = txt_uname.getText();
      char[] passwordChars = pwd_New_Password.getPassword();
      String New_Passwd = new String(passwordChars);
      passwordChars = pwd_Confirm_Password.getPassword();
      String Confirm_Passwd = new String(passwordChars);
       
       if (username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username field cannot be blank");
            return false;
        }
        if (New_Passwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "New Password field cannot be blank");
            return false;
        }
        if (Confirm_Passwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Confirm Password field cannot be blank");
            return false;
        }
        if (!New_Passwd.equals(Confirm_Passwd)) {
            JOptionPane.showMessageDialog(this, "New Password and Confirm Password do not match");
            return false;
        }
        return true;
    }
    
    //verify credentials
    public boolean updatePassword() {
      String username = txt_uname.getText();
    char[] passwordChars = pwd_New_Password.getPassword();
    String New_Passwd = new String(passwordChars);
    passwordChars = pwd_Confirm_Password.getPassword();
    String Confirm_Passwd = new String(passwordChars);

    // Check if the new password matches the confirmation password
    if (!New_Passwd.equals(Confirm_Passwd)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.");
        return false; // Passwords do not match
    }

    try (Connection con = DBConnection.getConnection()) {
        if (con == null || con.isClosed()) {
            JOptionPane.showMessageDialog(this, "Failed to establish a database connection.");
            return false;
        }

        String query = "UPDATE UserType SET Password = ? WHERE Username = ?";
        try (PreparedStatement pst = con.prepareStatement(query)) {
            pst.setString(1, New_Passwd);
            pst.setString(2, username);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Password Updated Successfully!");
                new Login().setVisible(true);
                dispose();
                return true; // Password update successful
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    return false; // Password update failed
      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel10 = new javax.swing.JLabel();
        Show_PasswordCheckBox = new javax.swing.JCheckBox();
        pwd_New_Password = new javax.swing.JPasswordField();
        pwd_Confirm_Password = new javax.swing.JPasswordField();
        btn_Update = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reset Password");

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reset Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 60, 200, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ArchiTech CAD Academy");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 10, 229, 30);
        jPanel2.add(txt_uname);
        txt_uname.setBounds(230, 150, 230, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 230, 170, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 140, 160, 35);

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/OIP copy.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage1);
        rSPanelImage1.setBounds(350, 10, 120, 120);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Password");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 190, 170, 35);

        Show_PasswordCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Show_PasswordCheckBox.setForeground(new java.awt.Color(255, 255, 0));
        Show_PasswordCheckBox.setText("Show Password");
        Show_PasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_PasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(Show_PasswordCheckBox);
        Show_PasswordCheckBox.setBounds(350, 260, 109, 20);
        jPanel2.add(pwd_New_Password);
        pwd_New_Password.setBounds(230, 190, 230, 22);
        jPanel2.add(pwd_Confirm_Password);
        pwd_Confirm_Password.setBounds(230, 230, 230, 22);

        btn_Update.setBackground(new java.awt.Color(0, 0, 153));
        btn_Update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 0));
        btn_Update.setText("Update");
        btn_Update.setBorder(null);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Update);
        btn_Update.setBounds(200, 340, 120, 40);

        btn_Back.setBackground(new java.awt.Color(0, 0, 153));
        btn_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 0));
        btn_Back.setText("Back");
        btn_Back.setBorder(null);
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Back);
        btn_Back.setBounds(230, 280, 80, 30);

        loginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show_PasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_PasswordCheckBoxActionPerformed
        if (Show_PasswordCheckBox.isSelected()) {
            pwd_New_Password.setEchoChar((char) 0); // Show password
        } else {
            pwd_Confirm_Password.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_Show_PasswordCheckBoxActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        if (validateInputs()) {
          updatePassword();
    }
        
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
       Login obj = new Login();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new reset_password().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Show_PasswordCheckBox;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField pwd_Confirm_Password;
    private javax.swing.JPasswordField pwd_New_Password;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
